export const API_ENDPOINTS = {
  page_details: `/pagedetail`,
  filters: "filters",
  products: "products",
  productsDetails: "product/detail",
  add_to_cart: "cart/add",
  cart_list : "carts",
  
  wishlistRemove : "wishlist/delete",
  wishlistAdd : "wishlist/add",
  wishlistGet : "wishlist",
  update_cart : "cart/update",
  delete_cart : "cart/delete",
  apply_coupon : "applycoupon",
  remove_coupon : "removecoupon",
  login : "login",
  login_verify_user_with_otp : "login_verify_user_with_otp",
  user_profile : "profile",
  cities : "cities",
  states : "state",
  checkout : "checkout",
  order : "order",
  order_detail : "order/detail",
  profileUpdate : "profileupdate",
  addreview : "order/addreview",
  checkoutpay : "checkoutpay",
  login_google : "login_google",
  blogs : "blogs",
  blogDetail : "blog/detail",
  contactus : "contactus",
  newsletter : "newsletter",
  category_banner : "category/detail",
  checkoutcart : "checkoutcart",
  checkoutaddress : "checkoutaddress",
  get_product_addons : "addonproducts",
  getShipping : "shipping",
  addToaddoncart : "addoncart/add",
  update_addon_cart : "addoncart/update",
  delete_addon_cart : "addoncart/delete",
  pincodes_by_city : "pincode"
  
  
};
